name: Docker Build & Publish

on:
  push:
    branches:
      - 'main'

permissions:
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_BASE_NAME: haspamelodica/studentcodeseparator

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      -
        name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: "Build and push: base"
        uses: docker/build-push-action@v2
        with:
          file: base.Dockerfile
          tags: ghcr.io/${{ env.IMAGE_BASE_NAME }}:base
          push: true
      -
        name: "Build and push: student-base"
        uses: docker/build-push-action@v2
        with:
          file: student-base.Dockerfile
          tags: ghcr.io/${{ env.IMAGE_BASE_NAME }}:student-base
          push: true
      -
        name: "Build and push: exercise"
        uses: docker/build-push-action@v2
        with:
          file: exercise.Dockerfile
          tags: ghcr.io/${{ env.IMAGE_BASE_NAME }}:exercise
          push: true
